#!/usr/bin/env bash
# ---------------------------------------------------------------------------
# Reads the Terraform outputs and writes the CANARY_* contract the other
# scripts consume.
#
#   ./scripts/load-env.sh
#   eval "$(./scripts/load-env.sh --export)"   # just this shell
# ---------------------------------------------------------------------------
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
# shellcheck source-path=SCRIPTDIR
# shellcheck source=lib.sh
. "${SCRIPT_DIR}/lib.sh"

TF_DIR="${SCRIPT_DIR}/../infra/terraform"
EXPORT_ONLY=false
PRINT_ONLY=false
QUIET=false

usage() {
  print_header_help "${BASH_SOURCE[0]}"
  cat <<'EOF'
Options
  --tf-dir PATH     Terraform directory (default: infra/terraform)
  --region REGION   AWS region for the lookup
  --export          Print `export VAR=...` lines instead of writing the file
  --print           Print the resolved values and exit without writing
  --quiet           Suppress the summary
  -h, --help        This help
EOF
}

while [ $# -gt 0 ]; do
  case "$1" in
    --tf-dir) TF_DIR="$2"; shift 2 ;;
    --region) export AWS_REGION="$2"; shift 2 ;;
    --export) EXPORT_ONLY=true; shift ;;
    --print) PRINT_ONLY=true; shift ;;
    --quiet) QUIET=true; shift ;;
    -h | --help) usage; exit 0 ;;
    *) err "unknown argument: $1"; usage >&2; exit 2 ;;
  esac
done

require_tools terraform jq
[ -d "$TF_DIR" ] || die "terraform directory not found: $TF_DIR"

CONTRACT_KEYS="CANARY_REGION CANARY_PROJECT CANARY_CLUSTER CANARY_ALB_DNS CANARY_ALB_ARN \
CANARY_LISTENER_ARN CANARY_TG_STABLE CANARY_TG_CANARY CANARY_SVC_STABLE CANARY_SVC_CANARY \
CANARY_TASKDEF_STABLE CANARY_TASKDEF_CANARY CANARY_ECR_REPO CANARY_ECR_URI CANARY_TABLE \
CANARY_LOG_GROUP CANARY_ALARM_5XX CANARY_ALARM_LATENCY CANARY_ALARM_UNHEALTHY \
CANARY_ALARM_ERRORRATE CANARY_CONTAINER_NAME CANARY_CONTAINER_PORT"

step "reading terraform outputs from ${TF_DIR}"
RESOLVED_JSON="$(terraform -chdir="$TF_DIR" output -json canary_env 2>/dev/null)" ||
  die "could not read the canary_env output. Has 'terraform apply' run in ${TF_DIR}?"
[ -n "$RESOLVED_JSON" ] && [ "$RESOLVED_JSON" != "null" ] || die "the canary_env output is empty"

REQUIRED_KEYS="CANARY_CLUSTER CANARY_ALB_DNS CANARY_LISTENER_ARN CANARY_TG_STABLE CANARY_TG_CANARY CANARY_SVC_STABLE CANARY_SVC_CANARY"
MISSING=""
for key in $REQUIRED_KEYS; do
  value="$(printf '%s' "$RESOLVED_JSON" | jq -r --arg k "$key" '.[$k] // ""')"
  [ -n "$value" ] && [ "$value" != "None" ] || MISSING="${MISSING} ${key}"
done
[ -z "$MISSING" ] || die "these outputs came back empty:${MISSING}"

render_exports() {
  local key value
  for key in $CONTRACT_KEYS; do
    value="$(printf '%s' "$RESOLVED_JSON" | jq -r --arg k "$key" '.[$k] // ""')"
    printf 'export %s=%s\n' "$key" "$(printf '%q' "$value")"
  done
}

render_env_file() {
  local key value
  printf '# Generated by scripts/load-env.sh on %s. Regenerate after every apply. Safe to delete.\n' \
    "$(date -u '+%Y-%m-%dT%H:%M:%SZ')"
  for key in $CONTRACT_KEYS; do
    value="$(printf '%s' "$RESOLVED_JSON" | jq -r --arg k "$key" '.[$k] // ""')"
    printf '%s=%s\n' "$key" "$value"
  done
}

if [ "$PRINT_ONLY" = true ]; then
  printf '%s\n' "$RESOLVED_JSON" | jq .
  exit 0
fi

if [ "$EXPORT_ONLY" = true ]; then
  render_exports
  exit 0
fi

render_env_file >"$ENV_FILE"

if [ "$QUIET" != true ]; then
  ok "wrote ${ENV_FILE}"
  printf '%s' "$RESOLVED_JSON" | jq -r '
    "  cluster    \(.CANARY_CLUSTER)",
    "  dashboard  http://\(.CANARY_ALB_DNS)",
    "  services   \(.CANARY_SVC_STABLE) | \(.CANARY_SVC_CANARY)",
    "  registry   \(.CANARY_ECR_URI)"
  ' >&2
  info "next: ./scripts/status.sh"
fi
